### ISSUE TITLE
The action 'new' could not be found for DeviseTokenAuth::RegistrationsController

### ISSUE THREAD

**Issue by baramik** [lynndylanhurley/devise_token_auth#100]
Hi, I faced some issue using gem.

I have got such routing
```ruby
require 'api_constraints'
CapperGroupV1::Application.routes.draw do
  namespace :api, defaults: { format: :json },
                              constraints: { subdomain: 'api' }, path: '/'  do
    scope module: :v1,
              constraints: ApiConstraints.new(version: 1, default: true) do
      mount_devise_token_auth_for 'User', at: '/auth'       
    end
  end
end 
```
And I got a result of my rake route :
```
new_api_user_registration 
GET /auth/sign_up(.:format)                
devise_token_auth/registrations#new {:format=>:json, :subdomain=>"api"}
```
But when i'm trying http://api.cappergroupv1.dev/auth/sign_up
I'm getting action missing error

Thanks in advance

**Comment by lynndylanhurley** [comment]
@baramik - I think this has been fixed in version `0.1.31.beta8`. Please confirm.

**Comment by lynndylanhurley** [comment]
@baramik - I originally thought that this issue was related to your use of `namespace`, which has been fixed as of the latest beta `0.1.31.beta8`, but I just realized that you're trying to access the `new` route of the `registrations_controller`. I'll repeat the response that I just gave in #105:

The new route isn't used by this gem. In standard devise, the new route is used for rendering the form's html page. This gem expects the form to be rendered by a front-end SPA (angualrjs, backbone, etc.).

I would like to disable the route completely, but according to this SO post, removing it will be more trouble than it's worth.

Let me know if the existence of the route is causing any serious problems, otherwise I'm closing this issue.

**Comment by andreydeineko** [comment]
@lynndylanhurley hey, so what is the right way to overcome the routes issue? I'm having really similar problem: #199 ..

**Comment by boyfunky** [comment]
I wanna get one understanding right. Do i have to get devise installed first in my Rails app before i can use the devise-token-auth gem to connect wt my angularJS part?

**Comment by boyfunky** [comment]
@baramik where u able to solve this issue? cant solve it and i hv been on it for over 2days

**Comment by boyfunky** [comment]
@andreydeineko  where u able to solve this issue?

**Comment by nicolas-besnard** [comment]
You don't need this route.

**Comment by boyfunky** [comment]
So if i need to register a new user and my front-end html is angularjs how do i route it to rails  similar to the sign_in method? @nicolas-besnard

**Comment by boyfunky** [comment]
i am using this tutorial https://www.airpair.com/ruby-on-rails/posts/authentication-with-angularjs-and-ruby-on-rails

**Comment by nicolas-besnard** [comment]
https://github.com/lynndylanhurley/ng-token-auth

**Comment by boyfunky** [comment]
yes @nicolas-besnard  im using devise-token-auth gem in rails and ng-token-auth in angularjs nd im getting that error

**Comment by nicolas-besnard** [comment]
You call the wrong URL, look at the doc.

**Comment by boyfunky** [comment]
i know the doc says emailRegistrationPath:   '/auth',  but in my routes.rb in rails 
mount_devise_token_auth_for 'User', at: 'auth' sets d url to be /auth/sign_up.  So even if i set it up to be the same route, i still end up with the same error 
The action 'new' could not be found for DeviseTokenAuth::RegistrationsController. I realised that one of the answer that @lynndylanhurley  gave he mentioned that the gem doesnt support the new method for registrations. So then how can i perform an email registration because following the docs i end up with the same error. Which has to do with the devise_token_auth not supporting the new method. How do i customize it then? if I dont need the route, then how do i replace it because i need to perform an email registration authentication in my app. Thanks @nicolas-besnard and i hope this isnt being of much trouble to u.

**Comment by n5ken** [comment]
@boyfunky the easiest way is to create your own controller and view like 'SessionController' and 'new.html.erb', don't care about the session_new_path any more, just imagine that devise_token_auth provide the login related methods (service) for you.

**Comment by philrosenstein** [comment]
is manually creating sessions_controller with empty create action, and the 'new' view, sufficient to use those parts of devise, or is better to install the device gem in addition to devise_token_auth ?

**Comment by Tr4pSt3R** [comment]
6years and still broken?

**Comment by lynndylanhurley** [comment]
@Tr4pSt3R this issue was closed 6 years ago. Please create a new ticket if you're having a different problem.

**Comment by Tr4pSt3R** [comment]
@lynndylanhurley Sure thanks for all your awesome work!
