### ISSUE TITLE
Using DeviseTokenAuth::Concerns::User breaks Devise::confirmable and Devise::reconfirmable

### ISSUE THREAD

**Issue by Marinlemaignan** [lynndylanhurley/devise_token_auth#1013]
Culprits being :
```
    # don't use default devise email validation
    def email_required?
      false
    end

    def email_changed?
      false
    end

    def will_save_change_to_email?
      false
    end
```
why is that

**Comment by zachfeldman** [comment]
Hi @Marinlemaignan , I haven't been here since day 1, but when going through the repo I did find a few references to confirmableand reconfirmable being broken.

We'd welcome your pull request if this is truly an issue!

**Comment by Marinlemaignan** [comment]
This breaks this part of the reconfirmable module:
```
        if Devise.activerecord51?
          def postpone_email_change?
            postpone = self.class.reconfirmable &&
              will_save_change_to_email? &&    ######### HERE
              !@bypass_confirmation_postpone &&
              self.email.present? &&
              (!@skip_reconfirmation_in_callback || !self.email_in_database.nil?)
            @bypass_confirmation_postpone = false
            postpone
          end
        else
          def postpone_email_change?
            postpone = self.class.reconfirmable &&
              email_changed? && ######### HERE
              !@bypass_confirmation_postpone &&
              self.email.present? &&
              (!@skip_reconfirmation_in_callback || !self.email_was.nil?)
            @bypass_confirmation_postpone = false
            postpone
          end
        end
```

**Comment by Marinlemaignan** [comment]
I'll try something out and will keep you updated as i can

**Comment by Marinlemaignan** [comment]
In the meantime this issue _should_ be referenced in the wiki, so that no one will loose time figuring out something that is already known

**Comment by zachfeldman** [comment]
Sure we currently have nothing in the Wiki most is in the README (I know, it's really hard to read but that's where we're at) - maybe a quick PR into there!

**Comment by zachfeldman** [comment]
Appreciate your possible contribution @Marinlemaignan !

**Comment by KelseyDH** [comment]
Yeah looking at how `devise` works internally, overwriting these User methods looks like a path down to unmaintainable insanity.  It complects this gem tremendously, and I'm not sure for what reasons.

E.g. devise's `confirmable` module uses methods like `will_save_change_to_email?` to implement important logic around safely confirming email's when they change... an important security constraint (otherwise an email for an account could be changed to something else and the user loses access!).  This gem throws all that out (and breaking devise in the process) for reasons I'm not sure about.

It would appear that whatever these overrides are trying to achieve, their path towards doing it is not a sane one.   I think a major reworking of this gem would be to reduce the amount of things about `devise` that `devise_token_auth` sticks its hands in, by not sticking its hands into anything beyond token authentication.

If its true that devise itself is far too coupled to web-based sessions/CSRF/Warden strategies to be monkey patched for api apps using token authentication... then it might just make sense to just fork devise completely, yank out the web app stuff requiring overrides, and make it a pure token authentication system with its model behaviour (mostly) unchanged.  Just a thought...

**Comment by lynndylanhurley** [comment]
@Marinlemaignan - I don't remember the reason exactly. I think it was just a hack to get OAuth login working. We should probably change those methods to return `provider == 'email'`.

Would you like to submit a PR?

**Comment by lynndylanhurley** [comment]
@KelseyDH - Thanks for your feedback. The default devise method did not work with OAuth login in cases where an email address was not given. I agree that this workaround is not ideal. Would you like to help us improve it?

**Comment by KelseyDH** [comment]
@lynndylanhurley  Thanks for getting back. I'm definitely interested, as I'm becoming rather well versed in this gem as a result of a few issues.

But I worry that people might be looking into specific problems with this gem, and implementing fixes or refactorings for them that only further complect things, rather than taking a step back and thinking about how we can restructure a gem like this to be as lightweight as possible.

E.g. it's clear that `devise` and `devise_token_auth` fundamentally differ with each other from one another by heavily relying on redirects and CSRF/Sessions/Cookies to do things, and the other being completely reliant on JSON/tokens.

This distinction should be preserved to the extent that guides make it clear all web sides of devise must go into one namespace, and all api sides of devise_token_auth into another with first class support for subclassing ApplicationController to achieve this so we can easily achieve true separation between web rails and API rails to the point where you could run separate apps for each endpoint pointing to the same database.

**Comment by mcelicalderon** [comment]
Not sure if I'm missing something, but this is still an issue, right? So the workaround for now is to reimplement this methods and return `provider == 'email'` instead of `false`, right? Creating a PR for this is something you would still be interested? @lynndylanhurley @Marinlemaignan @zachfeldman

**Comment by mcelicalderon** [comment]
Just to provide an update if it helps anyone.
Just adding this method on the mounted model (eg: User) fixes the problem
```ruby
# On ActiveRecord 5.1 and newer
def will_save_change_to_email?
  super
end

# On ActiveRecord < 5.1
def email_changed?
  super
end
```
You just need one of those depending on your AR version. I tested that it doesn't break any email authentication, registration, password recovery end points. I'm not using Omniauth so it might break something there as that is precisely why making this method always return `false` was introduced.
Just make sure this method definition goes below this line
`include DeviseTokenAuth::Concerns::User`

you will also need the default `confirm_success_url` on your initializer
```ruby
# config/initializers/devise_token_auth.rb
DeviseTokenAuth.setup do |config|
  config.default_confirm_success_url = 'https://google.com'
end
```

**Comment by gildo** [comment]
@mcelicalderon I've tried your method but apparently breaks the update on the email field (`put '/api/v1/auth/'` `params: {email: ....}`)
Any solution?
Thanks.
