### ISSUE TITLE
Why does update_auth_header need to query the resource for tokens again?

### ISSUE THREAD

**Issue by mtohmaz** [lynndylanhurley/devise_token_auth#1097]
First, devise token auth will query the user resource to verify the request. However, why does it have to make the same query in the `after_action`? It's causing two queries being made for the same information. Is there any way around this? We'd like to avoid the extra query.

* **Version**: 0.1.42

**Comment by zachfeldman** [comment]
@mtohmaz sure, seems wasteful to me? Maybe submit a PR so we can debate this further?

**Comment by MaicolBen** [comment]
@mtohmaz I believe that was fixed on #994, can you check on master if the query is done twice?

**Comment by MaicolBen** [comment]
One query was removed in that PR, but it still makes 2 queries to the user, one for checking if the user is valid and other for reloading the tokens in:

https://github.com/lynndylanhurley/devise_token_auth/blob/master/app/controllers/devise_token_auth/concerns/set_user_by_token.rb#L104

And that is a security issue, do you know a better solution? Otherwise I'm closing this
