### ISSUE TITLE
Using expired token for parallel calls

### ISSUE THREAD

**Issue by ACPK** [lynndylanhurley/devise_token_auth#123]
How can we have parallel calls?  For instance a user opens a page which initiates a request.  Before the response comes back, the app is ready to make another request and needs to send it to the server. In the current expired token use case, it seems that the app (iOS) request would have to wait in queue until the first request is done.

I was told that it would be coercive to try and make them batch requests.

**Comment by lynndylanhurley** [comment]
@ACPK - this is explained in detail [here](https://github.com/lynndylanhurley/devise_token_auth#about-batch-requests).

**Comment by npham1** [comment]
@lynndylanhurley  I read that but my iOS developer (Guy from Palo Alto who got his masters from Stanford) said that:

"Specially for our app where we might get very slim windows of time to run (at least on iOS), we can’t afford not to have parallel requests."

"I would still not recommend that. 1) because it limits parallel requests 2) if batch all requests coming from the app, it effectively becomes the scenario where the same token can be used for multiple requests."
