### ISSUE TITLE
access to current_user not available

### ISSUE THREAD

**Issue by pranavbhalla** [lynndylanhurley/devise_token_auth#1246]
Hi, 

Please let me know how to access current_staff (my Devise model is called 'Staff' instead of User) after logging in - 

I am sending request like this - curl -XGET -v -H 'Content-Type: application/json' http://localhost:3000/api/v1/calls/

But getting an error - NameError (uninitialized constant Api::V1::CallsController::AuthorizationException):
  
app/controllers/api/v1/calls_controller.rb:348:in `authenticate_staff!'

Do we need to send access token in the curl request every time ?

My calls_controller inherits the application controller 
class Api::V1::CallsController < Api::V1::ApplicationController

and my application controller - 
class Api::V1::ApplicationController < ActionController::API   #Note: here is not ::BASE
  include DeviseTokenAuth::Concerns::SetUserByToken

**Comment by MaicolBen** [comment]
hey @pranavbhalla !
did you look at the issues https://github.com/lynndylanhurley/devise_token_auth/issues?q=is%3Aissue+current_user+is%3Aclosed ? this is the most asked issues and it's common a missing configuration

> Do we need to send access token in the curl request every time ?
Yes,  otherwise how we determine which user is using the app? If you need more info, you can check https://devise-token-auth.gitbook.io/devise-token-auth/
