### ISSUE TITLE
Sign in via username doesn't seem to work correctly.

### ISSUE THREAD

**Issue by pjr0009** [lynndylanhurley/devise_token_auth#173]
I have a brand new rails api application, and a client side angular application. I can sign up perfectly fine, and log in perfectly fine using email / password. Then I change the form to pass "username" and "password" to the server and I get a 401. Is there some sort of special changes I need to make to enable this functionality that was added in: https://github.com/lynndylanhurley/devise_token_auth/pull/128

one possible issue is: https://github.com/lynndylanhurley/devise_token_auth/blob/master/app/controllers/devise_token_auth/sessions_controller.rb#L18

specifically the fact that "email" is hardcoded in there.

**Comment by lynndylanhurley** [comment]
Have you followed the [devise instructions for this](https://github.com/plataformatec/devise/wiki/How-To:-Allow-users-to-sign-in-using-their-username-or-email-address)?

**Comment by pjr0009** [comment]
@lynndylanhurley It seems like those docs are a little misleading or have a typo, I finally got it working. But on https://github.com/plataformatec/devise/wiki/How-To:-Allow-users-to-sign-in-using-their-username-or-email-address#tell-devise-to-use-username-in-the-authentication_keys

it said to add ":authentication_keys => [:login]" on the user model. However it wasn't until I changed that to :username that it worked

**Comment by lynndylanhurley** [comment]
Cool, thx for posting your solution :+1:

**Comment by paneer-tikka** [comment]
Hi, I'm running into the same issue. I have set `:authentication_keys => [:username]` and devise auth itself is working just fine. However, when I try to submit /sign_in request for token auth with `{"username":"foo", "password":"bar"}`, it fires a query the users table with a `provider='email'` in the where clause. Then it fails to find the user and gives a 401. This where clause appears to originate from https://github.com/lynndylanhurley/devise_token_auth/blob/master/app/controllers/devise_token_auth/sessions_controller.rb#L18 as discribed by @pjr0009. 
If I change the hard-coded 'email' provider to a hard-coded 'username', token auth works fine. Instead of the provider being hard-coded to 'email' (or whatever), shouldn't it be obtained from devise? I am probably missing something here... is there any configuration that I'm missing?

**Comment by sotayamashita** [comment]
```ruby
# models/user
class User < ApplicationRecord
  devise authentication_keys: [:username, :email]
```

**Comment by MarceloSantana7** [comment]
> Olá, estou com o mesmo problema. Eu configurei `:authentication_keys => [:username]`e concebi a própria autenticação está funcionando muito bem. No entanto, quando tento enviar a solicitação /sign_in para autenticação de token com `{"username":"foo", "password":"bar"}`, ele dispara uma consulta à tabela de usuários com um `provider='email'`na cláusula where. Em seguida, ele não consegue encontrar o usuário e fornece um 401. Esta cláusula where parece se originar de https://github.com/lynndylanhurley/devise_token_auth/blob/master/app/controllers/devise_token_auth/sessions_controller.rb#L18 conforme descrito por@pjr0009. Se eu alterar o provedor de 'email' codificado para um 'nome de usuário' codificado, a autenticação do token funcionará bem. Em vez de o provedor ser codificado para 'e-mail' (ou qualquer outra coisa), ele não deveria ser obtido do dispositivo? Provavelmente estou perdendo alguma coisa aqui ... há alguma configuração que estou perdendo?
> 
> ATUALIZAÇÃO: Deixando aqui caso alguém tenha um 'mal-entendido' semelhante. Depois de ler mais código, percebi que o uso de autenticação `username`é _um complemento_ `email` e não um _substituto da_ autenticação de e-mail, que era o que eu estava tentando alcançar.

Eu estava tentando fazer o mesmo! Na minha aplicação, um dos models só precisaria logar com username e senha, pois estes seriam criados pelo model de Admin.
