### ISSUE TITLE
Access to current_user variable?

### ISSUE THREAD

**Issue by kareemgrant** [lynndylanhurley/devise_token_auth#28]
I'm using devise_token_auth along with ng-token-auth library for my angular frontend and everything seems to be working well until I try to access the current_user variable to reference the signed in user. I looked at the code and see that you're using @current_user and that works temporarily, but after a few server requests, I lose reference to @current_user and the variable returns nil even though I have successfully logged in.  This prevents me from conducting simple authorization checks (for example: does the current_user belong to the requested account?). Is there something that I'm missing?

In a vanilla devise implementation, you would use a `before_action :authenticate_user!` in your controller to get access to the devise helper methods (current_user, user_signed_in?, etc). However, that is throwing an error as well. 

Thanks!

**Comment by edymerchk** [comment]
@kareemgrant did you find what was the issue?? I'm having a similar issue with rails-api

**Comment by aarmel-sw** [comment]
I had this same issue.  Its how it creates the current user. If you are using the namespace V1. it will actually create current_v1_user instead of current_user.

(at least with rails 5 beta 3 api option)
If you *DONT* put 'devise_for :users' below you will have the issue discussed.

Same goes for the other functions :authenticate_v1_user!

Rails.application.routes.draw do
  devise_for :users
  namespace :v1 do
    mount_devise_token_auth_for 'User', at: 'auth'
    resources :beer 
  end
end

Hope that helps.

GEMFILE
    devise (4.0.0.rc1)
      bcrypt (~> 3.0)
      orm_adapter (~> 0.1)
      railties (>= 4.1.0, < 5.1)
      responders
      warden (~> 1.2.3)
    devise_token_auth (0.1.37)
      devise (> 3.5.2, < 4.1)
      rails (< 6)

**Comment by ImDineshSaini** [comment]
How to pass token in header as it is not working in Rails 5

**Comment by Samuelodan** [comment]
Thank you, @aarmel-sw . I thought it was weird that Rails was suggesting I use `current_v1_user` and `authenticate_v1_user!` in the error when I had that Namespace.

I didn't think that was supposed to be happening.
