### ISSUE TITLE
remove unused nickname, image from user object

### ISSUE THREAD

**Issue by m2omou** [lynndylanhurley/devise_token_auth#304]
I want to remove the nickname and image from the user object as I don't need them.

I tried to override the assign_provider_attrs methods from the OmniauthCallbacks controller

config/routes.rb
```ruby
mount_devise_token_auth_for 'User', at: 'auth', controllers: {
                              omniauth_callbacks: 'overrides/omniauth_callbacks',
  }
```

controllers/overrides/omniauth_callbacks_controller.rb

```ruby
module Overrides
  class OmniauthCallbacksController < DeviseTokenAuth::OmniauthCallbacksController
    
    # break out provider attribute assignment for easy method extension
    def assign_provider_attrs(user, auth_hash)
      
      user.assign_attributes({
                                 email:    auth_hash['info']['email']
                             })
    end
  end
end
```

Did I missed something ? :) thanks

**Comment by booleanbetrayal** [comment]
You can just write a Rails migration to remove those columns and you should be good. The default generator supports them as they tend to be common fields for new projects. Hope this helps!

**Comment by lakesare** [comment]
what do rails migrations have to do with it? they are already not in my model and I'm getting
`ActiveRecord::UnknownAttributeError (unknown attribute 'nickname' for User.):`
errors correspondingly.

what is the usual way to use other column names (:name instead of :nickname) eg? overriding `assign_provider_attrs`?

**Comment by aeldaly** [comment]
bump! I do not understand why an assumption could be made that everyone has a nickname and image fields? And how is it that only 3 people on earth have that problem :D

**Comment by booleanbetrayal** [comment]
If someone feels passionately about this, then I'll accept a PR to that effect, so long as tests still pass.

**Comment by lynndylanhurley** [comment]
The reason those fields are used is because that's what's returned by OmniAuth. We could create an initializer setting for this, but it's also really easy to override [the controller method](https://github.com/lynndylanhurley/devise_token_auth/blob/master/app/controllers/devise_token_auth/omniauth_callbacks_controller.rb#L79) to not use those fields, and to remove the columns from the db migration. The amount of code written would be about the same, and the override is more flexible.

But I don't feel that strongly about it either way.

**Comment by chintans1** [comment]
Hi, I'm trying to remove the columns from the database but failing to do so. Is there something else needed to let me remove the columns?
