### ISSUE TITLE
Migrating from Devise

### ISSUE THREAD

**Issue by ianks** [lynndylanhurley/devise_token_auth#34]
If I were to move from Devise to this gem, what would be the easiest way to migrate over? All I have is a polymorphic user model which two attributes (email, password).

**Comment by c0mrade** [comment]
@lynndylanhurley @ianks @aihaddad why is this still closed it's still happening?

This is what I did :

1. Created new rails project (rails 4.2.0)
2. Added gems to my Gemfile 'devise_token_auth' and 'omniauth'
3. bundle install
4. rails g devise_token_auth:install
5. rake db:migrate

I still get validation error when I save the user for Validation failed: Uid can't be blank.
As pointed out in #29 that it's a bad idea. What is the alternative to this solution?

before_save -> do
    self.uid = SecureRandom.uuid
    skip_confirmation!
end

**Comment by lynndylanhurley** [comment]
@c0mrade - if you're using email authentication, the `uid` value should be identical to the user model's `email` value. The `uid` attribute will be set automatically if the `provider` attribute is set to `email` (which should be the case if you're using email authentication).

**Comment by c0mrade** [comment]
So you're saying that in my test factory (when I'm testing email authentication), both uid and provider should actually be users email?

And I should remove the part ``self.uid = SecureRandom.uuid`` from before_save callback on my model. Because it will be set by provider if I decide to use facebook/google.

Sorry if this is a dumb question, I'm new to all of this
