### ISSUE TITLE
Allow devise patch version updates

### ISSUE THREAD

**Issue by Dschee** [lynndylanhurley/devise_token_auth#351]
The most current 'devise' version is `3.5.2` but this gem specifies the exact version `3.5.1` which is too specific in my opinion. I can understand that there is the will to test things before upgrading but as this is a security aware and enhancing gem I feel it really should allow security patches and bug fixes to devise be immediately available.

I suggest using the `"~> 3.5.1"` specification style as this would allow others use 3.5.2 but not 3.6 until it is tested to work with 3.6+ versions.

**Comment by booleanbetrayal** [comment]
@Dschee - i agree with you, but explicitly pinned to 3.5.1 because 3.5.2 introduced changes that broke the BCrypt routines in devise_token_auth. As in, it completely broke the gem. These aren't caught in tests currently, either. I have been swamped and unable to dive into it further, but if you can get it working in 3.5.2 with verification tests, I can approve the pull.

**Comment by lynndylanhurley** [comment]
I'll have some time this weekend, I'll look into this ASAP.

**Comment by booleanbetrayal** [comment]
thanks @lynndylanhurley !

**Comment by lynndylanhurley** [comment]
@booleanbetrayal - I'm not seeing any errors with devise 3.5.2. Do you remember what the issue was specifically?

**Comment by booleanbetrayal** [comment]
@lynndylanhurley - Yeah, i'm no longer seeing this either. Wondering if it wasn't a fuzzy dependency issue pulling a temporarily broken BCrypt or something. Updated in bf2cc1b69a1456e53b40de87ec98245102d235a8

**Comment by Dschee** [comment]
@booleanbetrayal: Thank you for approving my pull request! :)

Never mind, I'll just close it.
