### ISSUE TITLE
Overriding render_create_success does not obey serializer option (AMS)

### ISSUE THREAD

**Issue by cireficc** [lynndylanhurley/devise_token_auth#890]
I wanted to override the JSON sent after successful sign in, so I did this:

```
# config/routes.rb
mount_devise_token_auth_for 'User', at: 'auth', controllers: { sessions: "sessions" }
```

```
# app/controllers/sessions_controller.rb
class SessionsController < DeviseTokenAuth::SessionsController
  def render_create_success
    render json: current_api_user, serializer: Api::V2::UserSerializer
  end
end
```

But the method did not respect the `serializer` option; it seemed to call `as_json` directly on the model object (unless I'm mistaken). However, building the json separately before calling `render` actually uses the active_model_serializers `UserSerializer`:

```
# app/controllers/sessions_controller.rb
class SessionsController < DeviseTokenAuth::SessionsController
  def render_create_success
    data = Api::V2::UserSerializer.new(current_api_user).as_json
    render json: data
  end
end
```

Is this a bug?

**Comment by dkniffin** [comment]
I ran into a similar issue. Here's my workaround:

```ruby
  def render_update_success
    render json: {
      status: "success",
      data: resource_data(
        resource_json: ActiveModel::SerializableResource.new(@resource).as_json
      )
    }
  end
```

_NOTE: Depending on your version of AMS, `ActiveModel::SerializableResource` might need to be replaced with `ActiveModelSerializers::SerializableResource`, but because of https://github.com/rails-api/active_model_serializers/issues/1667 / https://github.com/lynndylanhurley/devise_token_auth/issues/600, you're probably pinned to 0.10.0.rc4 like me, so the above is the version you want._

**Comment by zachfeldman** [comment]
Workaround posted, closing for now
